# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resume.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'resume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cresume.proto\"d\n\rResumeRequest\x12\x16\n\x0e\x63\x61ndidate_name\x18\x01 \x01(\t\x12\x13\n\x0bresume_text\x18\x02 \x01(\t\x12\x10\n\x08job_role\x18\x03 \x01(\t\x12\x14\n\x0clamport_time\x18\x04 \x01(\x03\"{\n\x0eResumeResponse\x12\x16\n\x0e\x63\x61ndidate_name\x18\x01 \x01(\t\x12\x13\n\x0bmatch_score\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x16\n\x0ematched_skills\x18\x04 \x01(\t\x12\x14\n\x0clamport_time\x18\x05 \x01(\x03\x32@\n\rResumeService\x12/\n\x0cScreenResume\x12\x0e.ResumeRequest\x1a\x0f.ResumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESUMEREQUEST']._serialized_start=16
  _globals['_RESUMEREQUEST']._serialized_end=116
  _globals['_RESUMERESPONSE']._serialized_start=118
  _globals['_RESUMERESPONSE']._serialized_end=241
  _globals['_RESUMESERVICE']._serialized_start=243
  _globals['_RESUMESERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
